import { chromium } from "playwright";
const errors = [];
const browser = await chromium.launch({ channel: "msedge" });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
page.setDefaultNavigationTimeout(90000);
page.on("pageerror", (e) => errors.push(String(e).slice(0, 140)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 140)); });
await page.goto("http://127.0.0.1:8082/?v=list", { waitUntil: "networkidle" });
await page.waitForTimeout(3000);
console.log("h1:", await page.locator("h1").first().textContent());
await page.getByRole("button", { name: /menu social/i }).click();
await page.waitForTimeout(600);
console.log("menu items:", await page.locator('[role="menuitem"]').count());
await page.screenshot({ path: "screenshots/shift-fixed.png" });
console.log("errors:", JSON.stringify([...new Set(errors)]));
await browser.close();
