/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiActivityRouteImport } from './routes/api/activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/share/$token': typeof ShareTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/activity': typeof ApiActivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/share/$token': typeof ShareTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/activity': typeof ApiActivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/share/$token': typeof ShareTokenRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/activity': typeof ApiActivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/login'
    | '/profile'
    | '/share/$token'
    | '/u/$username'
    | '/api/auth/$'
    | '/api/activity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/login'
    | '/profile'
    | '/share/$token'
    | '/u/$username'
    | '/api/auth/$'
    | '/api/activity'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/login'
    | '/profile'
    | '/share/$token'
    | '/u/$username'
    | '/api/auth/$'
    | '/api/activity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ShareTokenRoute: typeof ShareTokenRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiActivityRoute: typeof ApiActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ShareTokenRoute: ShareTokenRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiActivityRoute: ApiActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
